### PR TITLE
Fixed links and typo in ReadMe

### PR DESCRIPTION
**Pull request by digital-ember**

### CODE REVIEW

**Comment by debois** [comment]
Very good, thanks!

There was a request for more documentation on `render` and `create` in issue #6. I can see why that would be helpful, but I'm not sure what's the best way to go about it. Is that something you'd be interested in looking at?

**Comment by digital-ember** [comment]
Hi Søren,
I'd certainly benefit from a dedicated documentation on some of the
elm-parts' API.
I'll take a stab at it next week and see how it goes. No promises at that
point, though, since I'm new to Elm an I have to wrap my head around myself
first ;)

Best,
Robert

2016-07-13 10:30 GMT+02:00 Søren Debois notifications@github.com:

**Comment by debois** [comment]
Excellent!

Be sure to ask here or on the elm-slack (@debois) if you have questions or
want to discuss anything.

**Comment by digital-ember** [comment]
Hi Søren,

I was (and am) swamped with work these days (the merits of a freelancer, I
guess), so I hadn't had time to look at the issue. But I haven't forgotten
about it.
I'll let you know asap when I found some time to work on it.
Sorry,
Robert

2016-07-14 10:11 GMT+02:00 Søren Debois notifications@github.com:

**Comment by debois** [comment]
Hi Robert, 

No worries—I know what that's like :) Let me know if you find some time at some point!

Cheers,
Søren

**Pull request merged**
